### ISSUE TITLE
differ-cmdline/run.sh does not work

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#36] opened 2013-10-07 15:50 UTC
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'imageProcessor' defined in class path resource [pureImageProcessor.xml]: Cannot resolve reference to bean 'metadataExtractors' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metadataExtractors' defined in class path resource [appCtx-differ-common.xml]: Cannot resolve reference to bean 'imagemagickMetadataExtractor' while setting bean property 'extractors' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'imagemagickMetadataExtractor' defined in class path resource [imagemagickMetadataExtractor.xml]: Cannot resolve reference to bean 'units' while setting bean property 'units'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'units' is defined
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
    at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:630)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:148)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
    at cz.nkp.differ.cmdline.Main.main(Main.java:152)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metadataExtractors' defined in class path resource [appCtx-differ-common.xml]: Cannot resolve reference to bean 'imagemagickMetadataExtractor' while setting bean property 'extractors' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'imagemagickMetadataExtractor' defined in class path resource [imagemagickMetadataExtractor.xml]: Cannot resolve reference to bean 'units' while setting bean property 'units'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'units' is defined
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:353)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:153)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1360)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
    ... 17 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'imagemagickMetadataExtractor' defined in class path resource [imagemagickMetadataExtractor.xml]: Cannot resolve reference to bean 'units' while setting bean property 'units'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'units' is defined
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1360)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
    ... 29 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'units' is defined
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:553)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1095)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:277)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
    ... 39 more
jan@jan-XPS-L421X:/opt/differ/differ-cmdline$

**Comment by jstavel** [comment] 2013-10-07 15:51
I tried to set proper path to application.properties. It did not help.
Could you take a look at this problem?

Thank you,
Jan Stavel

**Comment by xrosecky** [comment] 2013-10-08 08:47
I can't reproduce your problem, do you use the latest version?

**Comment by jstavel** [comment] 2013-10-08 09:59
I was wrong.
I have merged all branches and it works well.

2013/10/8 Václav Rosecký notifications@github.com

> I can't reproduce your problem, do you use the latest version?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Differ-GSOC/differ/issues/36#issuecomment-25873535
> .

## 

Jan Stavìl
Pasovice 71,
tel: 733 230 772

**Comment by xrosecky** [comment] 2013-10-14 16:50
Closing this issue.

**Closed as completed by xrosecky** 2013-10-14 16:50 UTC
